site_name: AutoSettings Docs
pages:
    - Home: index.md
    - UMG Widgets: umg-widgets.md
    - Settings: settings.md
    - Input Binding: input-binding.md
    - Styling: styling.md
    - Example Project: example-project.md
    - Common Issues & FAQ: faq.md
    - Support: support.md
theme: readthedocs
